- name: 'package: halildurmus_hooks'
  color: '2FE436'
  description: Issue with package:halildurmus_hooks

- name: 'package: halildurmus_lints'
  color: '2FE436'
  description: Issue with package:halildurmus_lints

- name: 'package: next_version'
  color: '2FE436'
  description: Issue with package:next_version
